=== TimmiTBy/WebXML/electricalappliance.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema xmlns="http://www.w3.org/2001/XMLSchema"
        targetNamespace="http://www.example.com/Epam"
        xmlns:tns="http://www.example.com/Epam"
        elementFormDefault="qualified">

    <element name="device" type="tns:Device" abstract="true"></element>
    <element name="hairdryer" type="tns:Hairdryer" substitutionGroup="tns:device"></element>
    <element name="fridge" type="tns:Fridge" substitutionGroup="tns:device"></element>
    <element name="oven" type="tns:Oven" substitutionGroup="tns:device"></element>

    <element name="devices">
        <complexType>
            <sequence>
                <element ref="tns:device"  minOccurs="1" maxOccurs="unbounded"/>
            </sequence>
        </complexType>
    </element>

    <complexType name="Device">
        <sequence>
            <element name="is-on" type="boolean" default="false"/>
            <element name="power" type="positiveInteger"/>
            <element name="weight" type="positiveInteger"/>
            <element name="cost" type="positiveInteger"/>
        </sequence>
        <attribute name="id" type="ID" use="required"/>
    </complexType>

    <complexType name="Hairdryer">
        <complexContent>
            <extension base="tns:Device">
                <sequence>
                    <element name="wind-speed" type="positiveInteger"/>
                </sequence>
                <attribute name="brand" use="optional" default="N/A">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="Bosch"></enumeration>
                            <enumeration value="Rowenta"></enumeration>
                            <enumeration value="Philips "></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Fridge">
        <complexContent>
            <extension base="tns:Device">
                <sequence>
                    <element name="fridgeTemperature" type="positiveInteger"/>
                </sequence>
                <attribute name="brand" use="optional" default="N/A">
                    <simpleType>
                        <restriction base="string">
                            <enumeration value="Bosch"></enumeration>
                            <enumeration value="Samsung"></enumeration>
                            <enumeration value="LG"></enumeration>
                        </restriction>
                    </simpleType>
                </attribute>
            </extension>
        </complexContent>
    </complexType>

    <complexType name="Oven">
        <complexContent>
            <extension base="tns:Device">
                <sequence>
                    <element name="ovenTemperature" type="positiveInteger"/>
                </sequence>
                <attribute name="brand" use="required">
                </attribute>
            </extension>
        </complexContent>
    </complexType>

    <simpleType name="Device-id">
        <restriction base="ID">
            <pattern value="\d+"/>
        </restriction>
    </simpleType>


</schema>

=== TimmiTBy/WebXML/electricalappliance.xml
<?xml version="1.0" encoding="UTF-8"?>
<devices
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xmlns="http://www.example.com/Epam"
        xsi:schemaLocation="http://www.example.com/Epam electricalappliance.xsd">
    <hairdryer id="h1" brand="Rowenta">
      <is-on>false</is-on>
      <power>100</power>
      <weight>1</weight>
      <cost>60</cost>
      <wind-speed>70</wind-speed>
   </hairdryer>
   <hairdryer id="h2" brand="Bosch">
       <is-on>true</is-on>
       <power>150</power>
       <weight>1</weight>
       <cost>100</cost>
       <wind-speed>100</wind-speed>
   </hairdryer>
   <fridge id="f2" brand="Bosch">
       <is-on>true</is-on>
       <power>300</power>
       <weight>30</weight>
       <cost>900</cost>
       <fridgeTemperature>11</fridgeTemperature>
   </fridge>
   <oven id="o3" brand="Gefest">
       <is-on>true</is-on>
       <power>200</power>
       <weight>20</weight>
       <cost>600</cost>
       <ovenTemperature>20</ovenTemperature>
   </oven>
</devices>
